import type { Metadata } from "next";
import { Inter, Source_Code_Pro } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";

const inter = Inter({ subsets: ["latin"] });
const sourcecodepro = Source_Code_Pro({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WeatherProof",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sourcecodepro.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
